/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-ios-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.ios.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-id.yang */
public class tailfCiscoIosId extends ConfNamespace {
    public static final int hash = 539211867;
    public int hash() {
        return tailfCiscoIosId.hash;
    }

    public static final String id = "urn:ios-id";
    public String id() {
        return tailfCiscoIosId.id;
    }

    public static final String uri = "urn:ios-id";
    public String uri() {
        return tailfCiscoIosId.uri;
    }

    public static final String prefix = "ios-id";
    public String prefix() {
        return tailfCiscoIosId.prefix;
    }

    public tailfCiscoIosId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_ios = 1670740165;
    public static final String _cisco_ios_ = "cisco-ios";
}
